import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b0b0b',
  },
  scrollContent: {
    padding: 16,
  },
  previewScreen: {
    flex: 1,
    backgroundColor: '#0b0b0b',
    padding: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  logo: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1b06b',
  },
  title: {
    color: '#f5f0e6',
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  inputRow: {
    marginBottom: 12,
  },
  label: {
    color: '#bfae8a',
    marginBottom: 6,
    letterSpacing: 0.4,
  },
  input: {
    backgroundColor: '#141414',
    color: '#f5f0e6',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2b2b2b',
  },
  streamContainer: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2b2b2b',
  },
  streamOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  streamOverlayTitle: {
    color: '#f5f0e6',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  streamOverlayText: {
    color: '#bfae8a',
    textAlign: 'center',
  },
  streamReload: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#2b2b2b',
    backgroundColor: '#141414',
    marginBottom: 12,
  },
  streamReloadText: {
    color: '#d1b06b',
    fontSize: 12,
    letterSpacing: 0.3,
  },
  streamError: {
    color: '#d18b6b',
    fontSize: 12,
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#f5f0e6',
    fontWeight: '600',
    marginBottom: 6,
    letterSpacing: 0.4,
  },
  link: {
    color: '#d1b06b',
    letterSpacing: 0.3,
  },
  eventsList: {
    maxHeight: 180,
    marginBottom: 12,
  },
  eventsListFull: {
    flex: 1,
  },
  eventsContent: {
    gap: 8,
  },
  eventItem: {
    backgroundColor: '#141414',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2b2b2b',
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eventThumb: {
    width: 56,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#1b1b1b',
    borderWidth: 1,
    borderColor: '#2b2b2b',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  eventThumbImage: {
    width: '100%',
    height: '100%',
  },
  eventThumbLabel: {
    color: '#d1b06b',
    fontSize: 11,
    fontWeight: '700',
  },
  eventMeta: {
    flex: 1,
  },
  eventTitle: {
    color: '#f5f0e6',
    fontSize: 12,
    marginBottom: 4,
  },
  eventChevron: {
    color: '#bfae8a',
    fontSize: 22,
    marginLeft: 8,
  },
  eventPillRow: {
    marginTop: 6,
  },
  eventPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: '#2a2216',
    borderWidth: 1,
    borderColor: '#3b2d1a',
  },
  eventPillText: {
    color: '#d1b06b',
    fontSize: 10,
    fontWeight: '600',
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  filterChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#2b2b2b',
    backgroundColor: '#141414',
  },
  filterChipActive: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d1b06b',
    backgroundColor: '#d1b06b',
  },
  filterChipText: {
    color: '#f5f0e6',
    fontSize: 12,
  },
  filterChipActiveText: {
    color: '#1b1b1b',
    fontSize: 12,
    fontWeight: '700',
  },
  eventNav: {
    backgroundColor: '#141414',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2b2b2b',
    marginBottom: 12,
  },
  eventNavText: {
    color: '#f5f0e6',
    fontSize: 13,
  },
  eventText: {
    color: '#f5f0e6',
    fontSize: 12,
  },
  eventTime: {
    color: '#bfae8a',
    fontSize: 11,
    marginTop: 4,
  },
  mediaContainer: {
    height: 200,
    marginBottom: 12,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2b2b2b',
  },
  previewContainer: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2b2b2b',
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  notificationsContainer: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2b2b2b',
    backgroundColor: '#121212',
  },
  notificationsMeta: {
    color: '#9c8a63',
    fontSize: 11,
    marginBottom: 8,
  },
  notificationText: {
    color: '#bfae8a',
    fontSize: 12,
    marginBottom: 6,
  },
  emptyText: {
    color: '#bfae8a',
    textAlign: 'center',
    marginTop: 24,
  },
  button: {
    backgroundColor: '#d1b06b',
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: '#1b1b1b',
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  status: {
    color: '#bfae8a',
    marginTop: 12,
  },
  controlPad: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  controlButton: {
    backgroundColor: '#141414',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2b2b2b',
    paddingVertical: 10,
    paddingHorizontal: 16,
    minWidth: 52,
    alignItems: 'center',
  },
  controlButtonText: {
    color: '#f5f0e6',
    fontSize: 18,
    fontWeight: '600',
  },
  controlButtonAccent: {
    backgroundColor: '#d1b06b',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  controlButtonAccentText: {
    color: '#1b1b1b',
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  controlValue: {
    color: '#bfae8a',
    fontSize: 12,
  },
  controlStatusRow: {
    gap: 4,
    marginBottom: 8,
  },
  controlStatusText: {
    color: '#f5f0e6',
    fontSize: 12,
  },
  controlStatusError: {
    color: '#d18b6b',
    fontSize: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  stepButton: {
    borderWidth: 1,
    borderColor: '#2b2b2b',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#141414',
  },
  stepButtonActive: {
    borderWidth: 1,
    borderColor: '#d1b06b',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#d1b06b',
  },
  stepButtonText: {
    color: '#f5f0e6',
    fontSize: 12,
  },
  stepButtonActiveText: {
    color: '#1b1b1b',
    fontSize: 12,
    fontWeight: '700',
  },
  mediaActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 16,
    gap: 12,
    backgroundColor: '#0d0d0d',
    borderTopWidth: 1,
    borderTopColor: '#2b2b2b',
  },
  actionButton: {
    flex: 1,
    backgroundColor: '#d1b06b',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#d1b06b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonText: {
    color: '#0d0d0d',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  actionButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#d1b06b',
    shadowOpacity: 0,
    elevation: 0,
  },
  actionButtonSecondaryText: {
    color: '#d1b06b',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  recordingControls: {
    gap: 12,
    marginBottom: 16,
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  buttonDisabled: {
    backgroundColor: '#5a5040',
    opacity: 0.6,
  },
  linkDisabled: {
    fontSize: 14,
    color: '#6a8a6a',
    fontWeight: '600',
  },
  inputLabel: {
    color: '#bfae8a',
    marginBottom: 6,
    letterSpacing: 0.4,
    fontSize: 14,
  },
  updateButton: {
    backgroundColor: '#d1b06b',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  updateButtonText: {
    color: '#0b0b0b',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#0b0b0b',
  },
  modalContent: {
    padding: 24,
  },
  modalTitle: {
    color: '#f5f0e6',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 20,
    letterSpacing: 0.6,
  },
  modalText: {
    color: '#bfae8a',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 16,
  },
  modalSection: {
    marginTop: 24,
    marginBottom: 16,
  },
  modalSectionTitle: {
    color: '#f5f0e6',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 12,
    letterSpacing: 0.4,
  },
  modalButton: {
    backgroundColor: '#d1b06b',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 8,
  },
  modalButtonText: {
    color: '#0b0b0b',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  modalButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#d1b06b',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 8,
  },
  modalButtonSecondaryText: {
    color: '#d1b06b',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
})
