import { StyleSheet } from 'react-native'
import { Colors, Spacing, BorderRadius } from './colors'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  scrollContent: {
    padding: Spacing.base,
  },
  previewScreen: {
    flex: 1,
    backgroundColor: Colors.bgDark,
    padding: Spacing.base,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.md,
    paddingHorizontal: 4,
  },
  logo: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.primary,
    marginRight: Spacing.md,
  },
  title: {
    flex: 1,
    color: Colors.text,
    fontSize: 22,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
  settingsButton: {
    padding: Spacing.xs,
    marginLeft: Spacing.sm,
  },
  settingsIcon: {
    fontSize: 22,
    color: Colors.dimmed,
  },
  inputRow: {
    marginBottom: Spacing.md,
  },
  label: {
    color: Colors.secondary,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: '400',
  },
  input: {
    backgroundColor: Colors.cardHover,
    color: Colors.text,
    padding: 12,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    fontSize: 16,
  },
  streamContainer: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderColor,
  },
  streamOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.base,
  },
  streamOverlayTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
  },
  streamOverlayText: {
    color: Colors.secondary,
    textAlign: 'center',
  },
  streamReload: {
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primaryTransparent,
    marginBottom: Spacing.md,
  },
  streamReloadText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  streamError: {
    color: Colors.error,
    fontSize: 12,
    marginBottom: Spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  sectionTitle: {
    color: Colors.text,
    fontWeight: '600',
    marginBottom: 6,
    fontSize: 17,
  },
  link: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '500',
  },
  eventsList: {
    maxHeight: 180,
    marginBottom: Spacing.md,
  },
  eventsListFull: {
    flex: 1,
  },
  eventsContent: {
    gap: Spacing.sm,
    padding: Spacing.base,
  },
  eventItem: {
    backgroundColor: Colors.card,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderColor,
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  eventThumb: {
    width: 56,
    height: 42,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.cardHover,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  eventThumbImage: {
    width: '100%',
    height: '100%',
  },
  eventThumbLabel: {
    color: Colors.primary,
    fontSize: 11,
    fontWeight: '600',
  },
  eventMeta: {
    flex: 1,
  },
  eventTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  eventChevron: {
    color: Colors.dimmed,
    fontSize: 22,
    marginLeft: Spacing.sm,
  },
  eventPillRow: {
    marginTop: 6,
  },
  eventPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: Spacing.md,
    paddingVertical: 4,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primaryTransparent,
  },
  eventPillText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: '500',
  },
  filterRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.base,
  },
  filterChip: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: BorderRadius.pill,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    backgroundColor: Colors.card,
  },
  filterChipActive: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primary,
  },
  filterChipText: {
    color: Colors.secondary,
    fontSize: 14,
    fontWeight: '500',
  },
  filterChipActiveText: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  eventNav: {
    backgroundColor: Colors.card,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    marginBottom: Spacing.md,
  },
  eventNavText: {
    color: Colors.text,
    fontSize: 13,
  },
  eventText: {
    color: Colors.text,
    fontSize: 13,
  },
  eventTime: {
    color: Colors.dimmed,
    fontSize: 12,
    marginTop: 4,
  },
  mediaContainer: {
    height: 200,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderColor,
  },
  previewContainer: {
    flex: 1,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderColor,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  notificationsContainer: {
    marginTop: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    backgroundColor: Colors.card,
  },
  notificationsMeta: {
    color: Colors.dimmed,
    fontSize: 12,
    marginBottom: Spacing.sm,
  },
  notificationText: {
    color: Colors.secondary,
    fontSize: 13,
    marginBottom: 6,
  },
  emptyText: {
    color: Colors.dimmed,
    textAlign: 'center',
    marginTop: 24,
  },
  button: {
    backgroundColor: Colors.primary,
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
  },
  buttonText: {
    color: Colors.text,
    fontWeight: '500',
    fontSize: 16,
  },
  status: {
    color: Colors.dimmed,
    marginTop: Spacing.md,
    fontSize: 13,
  },
  controlPad: {
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  controlButton: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    paddingVertical: 10,
    paddingHorizontal: Spacing.base,
    minWidth: 52,
    alignItems: 'center',
  },
  controlButtonText: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: '500',
  },
  controlButtonAccent: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  controlButtonAccentText: {
    color: Colors.text,
    fontWeight: '500',
  },
  controlValue: {
    color: Colors.dimmed,
    fontSize: 12,
  },
  controlStatusRow: {
    gap: 4,
    marginBottom: Spacing.sm,
  },
  controlStatusText: {
    color: Colors.text,
    fontSize: 12,
  },
  controlStatusError: {
    color: Colors.error,
    fontSize: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  stepButton: {
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.card,
  },
  stepButtonActive: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primary,
  },
  stepButtonText: {
    color: Colors.secondary,
    fontSize: 14,
    fontWeight: '500',
  },
  stepButtonActiveText: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  mediaActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: Spacing.base,
    gap: Spacing.md,
    backgroundColor: Colors.bgDark,
    borderTopWidth: 1,
    borderTopColor: Colors.borderColor,
  },
  actionButton: {
    flex: 1,
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonText: {
    color: Colors.text,
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  actionButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: Colors.primary,
    shadowOpacity: 0,
    elevation: 0,
  },
  actionButtonSecondaryText: {
    color: Colors.primary,
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  recordingControls: {
    gap: Spacing.md,
    marginBottom: Spacing.base,
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  buttonDisabled: {
    backgroundColor: Colors.dimmed,
    opacity: 0.5,
  },
  linkDisabled: {
    fontSize: 14,
    color: Colors.dimmed,
    fontWeight: '500',
  },
  inputLabel: {
    color: Colors.secondary,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: '400',
  },
  updateButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginTop: Spacing.md,
  },
  updateButtonText: {
    color: Colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  modalContent: {
    padding: Spacing.xl,
  },
  modalTitle: {
    color: Colors.text,
    fontSize: 28,
    fontWeight: '600',
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  modalText: {
    color: Colors.secondary,
    fontSize: 16,
    lineHeight: 24,
    marginBottom: Spacing.base,
  },
  modalSection: {
    marginTop: Spacing.xl,
    marginBottom: Spacing.base,
  },
  modalSectionTitle: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: '600',
    marginBottom: Spacing.md,
  },
  modalButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginVertical: Spacing.sm,
  },
  modalButtonText: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  modalButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginVertical: Spacing.sm,
  },
  modalButtonSecondaryText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '500',
  },
})
