import { StyleSheet } from 'react-native'
import { Colors, Spacing, BorderRadius } from './colors'

export const F = {
  regular: 'Jost_400Regular',
  medium: 'Jost_500Medium',
  semibold: 'Jost_600SemiBold',
  bold: 'Jost_700Bold',
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  scrollContent: {
    paddingHorizontal: Spacing.base,
    paddingBottom: 32,
  },
  previewScreen: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Spacing.md,
    paddingBottom: Spacing.base,
    paddingHorizontal: 2,
  },
  logo: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.sm,
    marginRight: Spacing.sm,
  },
  title: {
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    color: Colors.text,
    fontSize: 20,
    fontFamily: F.semibold,
    letterSpacing: -0.4,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.chipBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsButton: {
    padding: Spacing.xs,
    marginLeft: Spacing.sm,
  },
  notificationsButton: {
    padding: Spacing.xs,
    marginLeft: 'auto',
  },
  // Status chips
  statusBar: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
    flexWrap: 'wrap',
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.chipBg,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  statusChipActive: {
    backgroundColor: Colors.successChipBg,
    borderColor: 'rgba(116, 170, 66, 0.2)',
  },
  statusChipWarning: {
    backgroundColor: 'rgba(255, 149, 0, 0.1)',
    borderColor: 'rgba(255, 149, 0, 0.2)',
  },
  statusChipText: {
    color: Colors.textDimmed,
    fontSize: 12,
    fontFamily: F.medium,
    letterSpacing: 0.1,
  },
  statusChipTextActive: {
    color: Colors.success,
  },
  statusChipTextWarning: {
    color: Colors.warning,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.dimmed,
  },
  statusDotActive: {
    backgroundColor: Colors.success,
  },
  statusDotWarning: {
    backgroundColor: Colors.warning,
  },
  inputRow: {
    marginBottom: Spacing.md,
  },
  label: {
    color: Colors.textSecondary,
    marginBottom: 6,
    fontSize: 13,
    fontFamily: F.medium,
    letterSpacing: 0.2,
  },
  input: {
    backgroundColor: Colors.cardHover,
    color: Colors.text,
    padding: 13,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    fontSize: 15,
    fontFamily: F.regular,
  },
  streamContainer: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderColor,
    backgroundColor: '#000',
  },
  // Viewfinder corner brackets
  streamCornerTL: {
    position: 'absolute', top: 10, left: 10,
    width: 18, height: 18,
    borderTopWidth: 2, borderLeftWidth: 2,
    borderColor: 'rgba(171, 201, 216, 0.45)',
    borderTopLeftRadius: 3,
  },
  streamCornerTR: {
    position: 'absolute', top: 10, right: 10,
    width: 18, height: 18,
    borderTopWidth: 2, borderRightWidth: 2,
    borderColor: 'rgba(171, 201, 216, 0.45)',
    borderTopRightRadius: 3,
  },
  streamCornerBL: {
    position: 'absolute', bottom: 10, left: 10,
    width: 18, height: 18,
    borderBottomWidth: 2, borderLeftWidth: 2,
    borderColor: 'rgba(171, 201, 216, 0.45)',
    borderBottomLeftRadius: 3,
  },
  streamCornerBR: {
    position: 'absolute', bottom: 10, right: 10,
    width: 18, height: 18,
    borderBottomWidth: 2, borderRightWidth: 2,
    borderColor: 'rgba(171, 201, 216, 0.45)',
    borderBottomRightRadius: 3,
  },
  streamLiveBadge: {
    position: 'absolute', top: 12, left: 12,
    flexDirection: 'row', alignItems: 'center', gap: 5,
    paddingVertical: 3, paddingHorizontal: 8,
    borderRadius: BorderRadius.pill,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  streamLiveDot: {
    width: 6, height: 6, borderRadius: 3,
    backgroundColor: Colors.success,
  },
  streamLiveText: {
    color: Colors.text,
    fontFamily: F.semibold,
    fontSize: 11,
    letterSpacing: 0.8,
  },
  streamOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.xl,
    gap: Spacing.sm,
  },
  streamOverlayTitle: {
    color: Colors.text,
    fontSize: 16,
    fontFamily: F.semibold,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  streamOverlayText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontFamily: F.regular,
    textAlign: 'center',
    lineHeight: 19,
    opacity: 0.8,
  },
  streamFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.sm,
    marginBottom: Spacing.base,
  },
  streamReload: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.chipBg,
  },
  streamReloadText: {
    color: Colors.primary,
    fontSize: 13,
    fontFamily: F.medium,
  },
  streamError: {
    color: Colors.error,
    fontSize: 12,
    fontFamily: F.regular,
    flex: 1,
    textAlign: 'right',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
    marginTop: Spacing.xs,
  },
  sectionTitle: {
    color: Colors.text,
    fontFamily: F.semibold,
    fontSize: 15,
    letterSpacing: -0.1,
  },
  link: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: F.medium,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.divider,
    marginVertical: Spacing.base,
  },
  eventsList: {
    maxHeight: 180,
    marginBottom: Spacing.md,
  },
  eventsListFull: {
    flex: 1,
  },
  eventsContent: {
    gap: Spacing.sm,
    paddingHorizontal: Spacing.base,
    paddingBottom: 24,
  },
  eventItem: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    overflow: 'hidden',
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.md,
    gap: Spacing.md,
  },
  eventThumb: {
    width: 64,
    height: 48,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.cardHover,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  eventThumbImage: {
    width: '100%',
    height: '100%',
  },
  eventThumbLabel: {
    color: Colors.primary,
    fontSize: 10,
    fontFamily: F.bold,
    letterSpacing: 0.5,
  },
  eventMeta: {
    flex: 1,
    gap: 3,
  },
  eventTitle: {
    color: Colors.text,
    fontSize: 13,
    fontFamily: F.medium,
    letterSpacing: -0.1,
  },
  eventChevron: {
    color: Colors.dimmed,
    fontSize: 20,
  },
  eventPillRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  eventPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.chipBg,
  },
  eventPillVideo: {
    backgroundColor: 'rgba(64, 114, 138, 0.18)',
  },
  eventPillRaw: {
    backgroundColor: 'rgba(255, 149, 0, 0.12)',
  },
  eventPillText: {
    color: Colors.primary,
    fontSize: 10,
    fontFamily: F.semibold,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  eventPillTextVideo: {
    color: Colors.secondary,
  },
  eventPillTextRaw: {
    color: Colors.warning,
  },
  filterRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  filterChip: {
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: BorderRadius.pill,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    backgroundColor: Colors.card,
  },
  filterChipActive: {
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primary,
    shadowColor: Colors.primaryGlow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 3,
  },
  filterChipText: {
    color: Colors.textDimmed,
    fontSize: 13,
    fontFamily: F.medium,
  },
  filterChipActiveText: {
    color: Colors.text,
    fontSize: 13,
    fontFamily: F.semibold,
  },
  eventNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.card,
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    marginBottom: Spacing.sm,
  },
  eventNavText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: F.medium,
  },
  eventNavChevron: {
    color: Colors.dimmed,
    fontSize: 18,
  },
  eventText: {
    color: Colors.text,
    fontSize: 13,
    fontFamily: F.regular,
  },
  eventTime: {
    color: Colors.dimmed,
    fontSize: 11,
    fontFamily: F.regular,
  },
  mediaContainer: {
    height: 200,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  previewContainer: {
    flex: 1,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  notificationsContainer: {
    marginTop: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    backgroundColor: Colors.card,
  },
  notificationsMeta: {
    color: Colors.dimmed,
    fontSize: 11,
    fontFamily: F.regular,
    marginBottom: Spacing.sm,
  },
  notificationText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontFamily: F.regular,
    marginBottom: 6,
    lineHeight: 18,
  },
  emptyText: {
    color: Colors.dimmed,
    textAlign: 'center',
    fontFamily: F.regular,
    fontSize: 14,
    marginTop: 48,
  },
  button: {
    backgroundColor: Colors.primary,
    paddingVertical: 15,
    paddingHorizontal: Spacing.xl,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(171, 201, 216, 0.18)',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.55,
    shadowRadius: 16,
    elevation: 8,
  },
  buttonText: {
    color: Colors.text,
    fontFamily: F.semibold,
    fontSize: 15,
    letterSpacing: 0.1,
  },
  status: {
    color: Colors.textDimmed,
    fontSize: 12,
    fontFamily: F.regular,
    marginBottom: Spacing.base,
    letterSpacing: 0.1,
  },
  controlPad: {
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  controlButton: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    paddingVertical: 10,
    paddingHorizontal: Spacing.base,
    minWidth: 52,
    alignItems: 'center',
  },
  controlButtonText: {
    color: Colors.text,
    fontSize: 18,
    fontFamily: F.medium,
  },
  controlButtonAccent: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  controlButtonAccentText: {
    color: Colors.text,
    fontFamily: F.medium,
  },
  controlValue: {
    color: Colors.dimmed,
    fontSize: 12,
  },
  controlStatusRow: {
    gap: 4,
    marginBottom: Spacing.sm,
  },
  controlStatusText: {
    color: Colors.text,
    fontSize: 12,
  },
  controlStatusError: {
    color: Colors.error,
    fontSize: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  stepButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    paddingVertical: 10,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    backgroundColor: Colors.card,
  },
  stepButtonActive: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderWidth: 1,
    borderColor: 'rgba(171, 201, 216, 0.18)',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.55,
    shadowRadius: 10,
    elevation: 6,
  },
  stepButtonText: {
    color: Colors.textDimmed,
    fontSize: 14,
    fontFamily: F.medium,
  },
  stepButtonActiveText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  durationRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  durationLabel: {
    color: Colors.textDimmed,
    fontSize: 11,
    fontFamily: F.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: Spacing.sm,
  },
  mediaActions: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
    gap: Spacing.sm,
    backgroundColor: Colors.bgDark,
    borderTopWidth: 1,
    borderTopColor: Colors.divider,
  },
  actionButton: {
    flex: 1,
    backgroundColor: Colors.primary,
    paddingVertical: 15,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    shadowColor: Colors.primaryGlow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 3,
  },
  actionButtonText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: F.semibold,
    letterSpacing: 0.2,
  },
  actionButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: Colors.primary,
    shadowOpacity: 0,
    elevation: 0,
  },
  actionButtonSecondaryText: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: F.semibold,
    letterSpacing: 0.2,
  },
  recordingControls: {
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  buttonDisabled: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonTextDisabled: {
    color: Colors.dimmed,
  },
  linkDisabled: {
    fontSize: 14,
    color: Colors.dimmed,
    fontFamily: F.medium,
    opacity: 0.5,
  },
  inputLabel: {
    color: Colors.textSecondary,
    marginBottom: 6,
    fontSize: 13,
    fontFamily: F.medium,
    letterSpacing: 0.2,
  },
  galleryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.base,
    borderBottomWidth: 1,
    borderBottomColor: Colors.divider,
  },
  galleryBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.chipBg,
  },
  galleryBackText: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: F.medium,
  },
  galleryTitle: {
    flex: 1,
    color: Colors.text,
    fontSize: 17,
    fontFamily: F.semibold,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  galleryCount: {
    width: 80,
    textAlign: 'right',
    color: Colors.dimmed,
    fontSize: 13,
    fontFamily: F.regular,
  },
  updateButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginTop: Spacing.md,
  },
  updateButtonText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  modalContent: {
    padding: Spacing.xl,
  },
  modalTitle: {
    color: Colors.text,
    fontSize: 26,
    fontFamily: F.bold,
    marginBottom: 20,
    letterSpacing: -0.6,
  },
  modalText: {
    color: Colors.textSecondary,
    fontSize: 15,
    fontFamily: F.regular,
    lineHeight: 23,
    marginBottom: Spacing.base,
  },
  modalSection: {
    marginTop: Spacing.xl,
    marginBottom: Spacing.base,
  },
  modalSectionTitle: {
    color: Colors.text,
    fontSize: 18,
    fontFamily: F.semibold,
    marginBottom: Spacing.md,
    letterSpacing: -0.3,
  },
  modalButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 15,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginVertical: Spacing.sm,
    shadowColor: Colors.primaryGlow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  modalButtonText: {
    color: Colors.text,
    fontSize: 15,
    fontFamily: F.semibold,
    letterSpacing: 0.1,
  },
  modalButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginVertical: Spacing.sm,
  },
  modalButtonSecondaryText: {
    color: Colors.primary,
    fontSize: 15,
    fontFamily: F.semibold,
    letterSpacing: 0.1,
  },
})
